// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf59DBnbmA3RGt-CfjVWxsXYNUNXXwrQc',
    appId: '1:323984253159:web:4a00d0b6429638cd754242',
    messagingSenderId: '323984253159',
    projectId: 'workshop-3800e',
    authDomain: 'workshop-3800e.firebaseapp.com',
    storageBucket: 'workshop-3800e.firebasestorage.app',
    measurementId: 'G-HW6V1Q3R1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AQo7ALMDg1IdqbURX1jBwpb5uwr5ZxE',
    appId: '1:323984253159:android:a805b467a11c8d1b754242',
    messagingSenderId: '323984253159',
    projectId: 'workshop-3800e',
    storageBucket: 'workshop-3800e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnim6Rrw60PHBrtyfYKpzDZEo0xgg3uPc',
    appId: '1:323984253159:ios:8fd98e6efaa70036754242',
    messagingSenderId: '323984253159',
    projectId: 'workshop-3800e',
    storageBucket: 'workshop-3800e.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnim6Rrw60PHBrtyfYKpzDZEo0xgg3uPc',
    appId: '1:323984253159:ios:8fd98e6efaa70036754242',
    messagingSenderId: '323984253159',
    projectId: 'workshop-3800e',
    storageBucket: 'workshop-3800e.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf59DBnbmA3RGt-CfjVWxsXYNUNXXwrQc',
    appId: '1:323984253159:web:c621d72fcbf800ed754242',
    messagingSenderId: '323984253159',
    projectId: 'workshop-3800e',
    authDomain: 'workshop-3800e.firebaseapp.com',
    storageBucket: 'workshop-3800e.firebasestorage.app',
    measurementId: 'G-QH7LZK34BT',
  );
}
